---
ci:
  autoupdate_schedule: monthly
  autoupdate: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Use the latest version or the version you prefer
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [--maxkb=99000]
      - id: check-json
      - id: check-yaml
      - id: check-case-conflict
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: name-tests-test
        args: [--pytest-test-first]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]

  - repo: https://github.com/albertas/deadcode
    rev: 2.4.1
    hooks:
      - id: deadcode

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1  # Use the latest version or the version you prefer
    hooks:
      - id: yamllint
        args: [--strict]

  - repo: https://github.com/econchick/interrogate
    rev: 1.7.0  # or master if you're bold
    hooks:
      - id: interrogate
        args: [--fail-under=95]
        pass_filenames: false  # needed if excluding files with pyproject.toml or setup.cfg

  - repo: https://github.com/google/pre-commit-tool-hooks
    rev: v1.2.5  # Use the rev you want to point at.
    hooks:
      - id: check-google-doc-style
      - id: markdown-toc

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2  # Use the latest version or the version you prefer
    hooks:
      - id: mypy
        args: ["--strict"]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest --cov=src --cov-report=term-missing --tb=short --disable-warnings
        language: system
        types: [python]
